// material-system/src/views/common/DomainManagement.vue
<template>
  <SmartListTemplate
    v-model:filter-model-value="filterParams"
    :fields="fields"
    :data-source="dataSource"
    :loading="loading"
    :title="pageTitle"
    :pagination="pagination"
    view-endpoint="/api/views"
    view-type="domain-management"
    @search="handleSearch"
    @reset="handleReset"
  >
    <template #toolbar-actions>
      <a-space :size="12">
        <a-button type="primary" @click="handleAdd">
          新增域
        </a-button>
        <ColumnSettingsPanel
          :fields="columnFields"
          :default-fields="defaultColumnFields"
          :exclude-keys="[]"
          @confirm="handleColumnSettingsConfirm"
          @reset="handleColumnSettingsReset"
        />
        <a-button class="icon-only-btn" @click="refresh" style="width: 32px; height: 32px; padding: 0;">
          <svg viewBox="0 0 48 48" style="width:16px;height:16px"><use href="#refresh" /></svg>
        </a-button>
      </a-space>
    </template>
    <template #bodyCell="{ column, record }">
      <template v-if="column.key === 'isDefault'">
        {{ record.isDefault === 1 ? '默认域' : '自定义域' }}
      </template>
      <template v-else-if="column.key === 'menuCount'">
        {{ record.menuCount || 0 }}个
      </template>
      <template v-else-if="column.key === 'userCount'">
        {{ record.userCount || 0 }}人
      </template>
      <template v-else-if="column.key === 'status'">
        <a-tag :color="record.status === 1 ? 'success' : 'default'">
          {{ record.status === 1 ? '启用' : '禁用' }}
        </a-tag>
      </template>
      <template v-else-if="column.key === 'action'">
        <ActionCell :buttons="getActionButtons(record)" />
      </template>
    </template>
  </SmartListTemplate>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import SmartListTemplate from '@/components/SmartListTemplate.vue'
import ActionCell from '@/components/ActionCell.vue'
import ColumnSettingsPanel from '@/components/ColumnSettingsPanel.vue'
import { useDomains } from '@/composables'

const router = useRouter()

const {
  loading,
  dataSource,
  pagination,
  filterParams,
  fetchData,
  refresh,
  updateDomainStatus,
  deleteDomain,
} = useDomains()

const fields = [
  { key: 'domainKey', label: '域标识', type: 'input' as const, width: 150 },
  { key: 'domainName', label: '域名称', type: 'input' as const, width: 150 },
  { key: 'isDefault', label: '域类型', type: 'input' as const, width: 100 },
  { key: 'menuCount', label: '包含菜单数', type: 'input' as const, width: 100 },
  { key: 'userCount', label: '用户数', type: 'input' as const, width: 80 },
  { key: 'status', label: '状态', type: 'select' as const, options: [
    { label: '全部', value: '' },
    { label: '启用', value: 1 },
    { label: '禁用', value: 0 }
  ], width: 100 },
  { key: 'action', label: '操作', width: 150 }
]

interface ColumnField {
  key: string
  label: string
  visible: boolean
  width?: number
  fixed?: 'left' | 'right' | undefined
}

const defaultColumnFields: ColumnField[] = fields
  .filter(field => field.key !== 'action')
  .map(field => ({
    key: field.key,
    label: field.label,
    visible: true,
    width: field.width,
  }))

const columnFields = ref<ColumnField[]>([])

function initColumnFields() {
  columnFields.value = JSON.parse(JSON.stringify(defaultColumnFields))
}

function loadColumnSettings() {
  try {
    const saved = localStorage.getItem('domain-management-column-settings')
    if (saved) {
      const savedFields = JSON.parse(saved)
      if (Array.isArray(savedFields) && savedFields.length > 0) {
        columnFields.value = savedFields
        return
      }
    }
  } catch (e) {
    console.error('加载列设置失败', e)
  }
  initColumnFields()
}

function saveColumnSettings() {
  try {
    localStorage.setItem('domain-management-column-settings', JSON.stringify(columnFields.value))
  } catch (e) {
    console.error('保存列设置失败', e)
  }
}

function handleColumnSettingsConfirm(fields: ColumnField[]) {
  columnFields.value = fields
  saveColumnSettings()
}

function handleColumnSettingsReset() {
  columnFields.value = JSON.parse(JSON.stringify(defaultColumnFields))
  saveColumnSettings()
}

const pageTitle = '域管理'

function handleSearch() {
  fetchData(filterParams.value)
}

function handleReset() {
  Object.assign(filterParams.value, { domainName: '', status: '' })
  pagination.value.current = 1
  fetchData(filterParams.value)
}

function handleAdd() {
  router.push('/domain-manage/create')
}

function handleEdit(record: any) {
  router.push(`/domain-manage/${record.id}`)
}

function getActionButtons(record: any) {
  const buttons = [
    { key: 'edit', label: '编辑', onClick: () => handleEdit(record) },
    { key: 'toggle', label: record.status === 1 ? '禁用' : '启用', onClick: () => handleToggleStatus(record) }
  ]
  if (record.isDefault !== 1) {
    buttons.push({ key: 'delete', label: '删除', onClick: () => handleDelete(record) })
  }
  return buttons
}

async function handleToggleStatus(record: any) {
  const success = await updateDomainStatus(record.id, record.status === 1 ? 0 : 1)
  if (success) {
    refresh()
  }
}

async function handleDelete(record: any) {
  const success = await deleteDomain(record.id)
  if (success) {
    refresh()
  }
}

onMounted(() => {
  fetchData()
  loadColumnSettings()
})
</script>

// react-system/src/pages/common/DomainManagement.tsx
import { useEffect, useCallback, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Tag, Space } from 'antd'
import {
  ActionCell,
  CompanyButton,
  CompanyMessage,
  SmartListTemplate,
  SvgIcon,
  ColumnSettingsPanel,
  type ColumnField,
  type FieldDefinition,
} from '@donglegeyu/company-ui'
import { API_ENDPOINTS } from '@/constants/api'
import { useListData } from '@/hooks'

interface DomainRecord {
  id: number
  domainKey: string
  domainName: string
  description: string
  isDefault: number
  menuCount?: number
  userCount?: number
  status: number
  createTime: string
  updateTime: string
}

const fields: FieldDefinition[] = [
  { key: 'domainKey', label: '域标识', type: 'input', placeholder: '请输入域标识', width: 150 },
  { key: 'domainName', label: '域名称', type: 'input', placeholder: '请输入域名称', width: 150 },
  { key: 'isDefault', label: '域类型', type: 'input', width: 100 },
  { key: 'menuCount', label: '包含菜单数', type: 'input', width: 100 },
  { key: 'userCount', label: '用户数', type: 'input', width: 80 },
  { key: 'status', label: '状态', type: 'select', width: 100, options: [
    { label: '全部', value: '' },
    { label: '启用', value: 1 },
    { label: '禁用', value: 0 },
  ]},
  { key: 'action', label: '操作', width: 148, fixed: 'right' },
]

const defaultColumnFields: ColumnField[] = [
  { key: 'domainKey', label: '域标识', visible: true, width: 150 },
  { key: 'domainName', label: '域名称', visible: true, width: 150 },
  { key: 'isDefault', label: '域类型', visible: true, width: 100 },
  { key: 'menuCount', label: '包含菜单数', visible: true, width: 100 },
  { key: 'userCount', label: '用户数', visible: true, width: 80 },
  { key: 'status', label: '状态', visible: true, width: 100 },
]

const STORAGE_KEY = 'domain-management-column-settings'

export default function DomainManagement() {
  const navigate = useNavigate()
  const { loading, dataSource, pagination, filterParams, setFilterParams, fetchData, refresh } = useListData<DomainRecord>({
    apiEndpoint: API_ENDPOINTS.DOMAINS,
    defaultPageSize: 20,
  })

  const [columnFields, setColumnFields] = useState<ColumnField[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY)
      if (saved) {
        const parsed = JSON.parse(saved)
        if (Array.isArray(parsed) && parsed.length > 0) return parsed
      }
    } catch { /* ignore */ }
    return defaultColumnFields
  })

  const handleColumnSettingsConfirm = useCallback((fields: ColumnField[]) => {
    setColumnFields(fields)
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(fields))
    } catch { /* ignore */ }
  }, [])

  const handleColumnSettingsReset = useCallback(() => {
    setColumnFields(defaultColumnFields)
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultColumnFields))
    } catch { /* ignore */ }
  }, [])

  const handleAdd = useCallback(() => {
    navigate('/domain-manage/create')
  }, [navigate])

  const handleEdit = useCallback((record: DomainRecord) => {
    navigate(`/domain-manage/${record.id}`)
  }, [navigate])

  const handleToggleStatus = useCallback(async (record: DomainRecord) => {
    const newStatus = record.status === 1 ? 0 : 1
    try {
      const res = await fetch(`${API_ENDPOINTS.DOMAINS}/${record.id}/status`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus }),
      })
      const json = await res.json()
      if (json.code === 200) {
        CompanyMessage.success(newStatus === 1 ? '已启用' : '已禁用')
        refresh()
      } else {
        CompanyMessage.error(json.message || '操作失败，请稍后重试')
      }
    } catch {
      CompanyMessage.error('操作失败，请稍后重试')
    }
  }, [refresh])

  const handleDelete = useCallback(async (record: DomainRecord) => {
    try {
      const res = await fetch(`${API_ENDPOINTS.DOMAINS}/${record.id}`, {
        method: 'DELETE',
      })
      const json = await res.json()
      if (json.code === 200) {
        CompanyMessage.success('删除成功')
        refresh()
      } else {
        CompanyMessage.error(json.message || '删除失败，请稍后重试')
      }
    } catch {
      CompanyMessage.error('删除失败，请稍后重试')
    }
  }, [refresh])

  const toolbarActions = (
    <Space size={12}>
      <CompanyButton type="primary" onClick={handleAdd}>
        新增域
      </CompanyButton>
      <ColumnSettingsPanel
        fields={columnFields}
        defaultFields={defaultColumnFields}
        excludeKeys={[]}
        onConfirm={handleColumnSettingsConfirm}
        onReset={handleColumnSettingsReset}
      />
      <CompanyButton
        onClick={refresh}
        style={{ width: 32, height: 32, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', padding: 0 }}
      >
        <SvgIcon href="refresh" size={16} />
      </CompanyButton>
    </Space>
  )

  const bodyCell = useCallback(
    (column: Record<string, unknown>, record: Record<string, unknown>) => {
      const domainRecord = record as unknown as DomainRecord

      if (column.key === 'isDefault') {
        return <>{domainRecord.isDefault === 1 ? '默认域' : '自定义域'}</>
      }

      if (column.key === 'menuCount') {
        return <>{domainRecord.menuCount || 0}个</>
      }

      if (column.key === 'userCount') {
        return <>{domainRecord.userCount || 0}人</>
      }

      if (column.key === 'status') {
        return (
          <Tag color={domainRecord.status === 1 ? 'success' : 'default'}>
            {domainRecord.status === 1 ? '启用' : '禁用'}
          </Tag>
        )
      }

      if (column.key === 'action') {
        const buttons = [
          { key: 'edit', label: '编辑', onClick: () => handleEdit(domainRecord) },
          {
            key: 'toggle',
            label: domainRecord.status === 1 ? '禁用' : '启用',
            onClick: () => handleToggleStatus(domainRecord),
          },
        ]
        if (domainRecord.isDefault !== 1) {
          buttons.push({
            key: 'delete',
            label: '删除',
            danger: true,
            confirm: true,
            confirmTitle: '确定删除？',
            onClick: () => handleDelete(domainRecord),
          })
        }
        return <ActionCell buttons={buttons} />
      }

      return null
    },
    [handleEdit, handleToggleStatus, handleDelete]
  )

  useEffect(() => {
    fetchData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <SmartListTemplate
      title="域管理"
      fields={fields}
      dataSource={dataSource}
      loading={loading}
      pagination={pagination}
      filterParams={filterParams}
      onFilterParamsChange={setFilterParams}
      onSearch={(data) => fetchData(data)}
      onReset={() => {
        setFilterParams({})
        fetchData({})
      }}
      columnFields={columnFields}
      defaultColumnFields={defaultColumnFields}
      onColumnSettingsChange={handleColumnSettingsConfirm}
      onColumnSettingsReset={handleColumnSettingsReset}
      onRefresh={refresh}
      toolbarActions={toolbarActions}
      bodyCell={bodyCell}
    />
  )
}
